import { Header } from '@/components/body/Header'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ weight: ['400', '700'] , subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section lang="en">
      <div className={roboto.className}>
        <Header />
        {children}
      </div>
    </section>
  )
}
