'use client'

import { Header } from '@/components/body/Header'
import { NavMenu } from '@/components/body/NavMenu'
import { LayoutContext } from '@/contexts/LayoutContext'
import { Roboto } from 'next/font/google'
import { useContext } from 'react'

const roboto = Roboto({ weight: ['400', '700'] , subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const {showNavMenu} = useContext(LayoutContext)
  return (
    <section lang="en">
      <div className={`flex ${roboto.className}`}>
        { showNavMenu && <NavMenu /> }
        <div className='flex flex-col w-screen'>
          <Header />
          {children}
        </div>
      </div>
    </section>
  )
}
